# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('language_code', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('content', models.TextField(verbose_name='code')),
                ('highlighted_content', models.TextField(verbose_name='highlighted code')),
                ('slug', models.SlugField(max_length=8, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('accessibility', models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Unlisted'), (2, 'Logged users'), (3, 'Private')], default=1, verbose_name='accessibility')),
                ('expiration', models.DateTimeField(blank=True, help_text='leave empty to keep forever', null=True, verbose_name='expiration')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippet.Language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
